AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an ec2 instance"

Parameters: 
  InstanceTypeParameter:
    Description: Select instance Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default id t2.micro

Resources: 
  Instance: #logical ID
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0928f4202481dfdf6